"""add is_personal to organizations

Revision ID: 0c823846db75
Revises: 0cb8a8ff6e64
Create Date: 2026-05-24 08:55:47.092383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c823846db75'
down_revision: Union[str, Sequence[str], None] = '0cb8a8ff6e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('is_personal', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'is_personal')
    # ### end Alembic commands ###
